### ISSUE TITLE
Moving to serverless architecture?

### ISSUE THREAD

**Issue by naveen521kk** [ManimCommunity/manim-website-api#38]
I think this app can be rewritten using a serverless architecture using cloud functions (and all) while also using a hosted version of MySQL (I got to know about planetscale recently). For updating the videos we can use GitHub Actions and modify the DB.

Also, we could apply for some sponsorship, say from Vercel, if we are exceeding their free limits, see https://vercel.com/guides/can-vercel-sponsor-my-open-source-project. Though first, we would need to decide on the stack we are going to use.

It would be great to hear some thoughts about this.

## Why?

Currently, this app is hosted in Oracle Cloud's free tier. Since we are only using the free tier sometimes the resource is automatically deallocated which is making things really *difficult*. The app was down for a few days (not sure how long) this month and I haven't noticed it until I was trying to do regular server maintenance. It was quite tedious setting up the server from scratch again (though most of it is automated with scripts).

Doing some analysis with logs I have from the server (from the 5th of this month), there are around 6k requests and only 2.5k of them are legit requests. Others seem to be spam or other tools trying to do something. All these can be avoided if we were using serverless architecture.

Either we should host it elsewhere, or rewrite this using a completely different architecture. That's why I created this issue to discuss.

cc @prism0x @behackl

**Comment by sujaldev** [comment]
> Since we are only using the free tier sometimes the resource is automatically deallocated which is making things really difficult

I usually get an email if this happens.

**Comment by sujaldev** [comment]
The purpose of this project is just to serve [this](https://www.manim.community/awesome/) page, right? If so, a single (or multiple for lazy loading) json file in a repository that the frontend could read might work. It's free and stupid simple :)

**Comment by naveen521kk** [comment]
This is done now!
